### ISSUE TITLE
Missing from maven central

### ISSUE THREAD

**Issue by UgmaDevelopment** [nikolaybespalov/winsw-maven-plugin#3]
Hello!

Thank you for writing this plugin! 

I've been looking for a while now, but am unable to find your plugin on Maven Central, or anywhere else. The readme badge also indicates it not being found: 
![image](https://user-images.githubusercontent.com/19827042/103854142-ff02dd80-506c-11eb-97b5-7cae5c33cab8.png)

Am I missing something?

**Comment by UgmaDevelopment** [comment]
If it's helpful—and you might already know this—but you can [publish Java packages right to GitHub](https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-java-packages-with-maven) now, apparently.

**Comment by nikolaybespalov** [comment]
Hello

Thank you for your interest. I will try to add artifacts to Maven Central today.

**Comment by nikolaybespalov** [comment]
I uploaded artifacts to Maven Central. Check it pls.

**Comment by UgmaDevelopment** [comment]
Hmm. I don't see  one for winsw-maven-plugin

![image](https://user-images.githubusercontent.com/19827042/103946647-1b962880-50f4-11eb-9060-60a0dceab8d8.png)

**Comment by nikolaybespalov** [comment]
It looks like the artifacts are still not distributed across the nodes
![2021-01-08_01-39-10](https://user-images.githubusercontent.com/756583/103953188-b6bdeb00-5152-11eb-929d-abb48aff8934.png)

**Comment by nikolaybespalov** [comment]
[Some information about this](https://stackoverflow.com/questions/23235892/how-long-does-sonatype-staging-take-to-sync-my-artifacts-with-maven-central)
