### ISSUE TITLE
Add support for classifier when pulling WinSW binary

### ISSUE THREAD

**Issue by s2131** [nikolaybespalov/winsw-maven-plugin#5]
It would be nice to add support for a classifier while pulling WinSW binary from Maven repo, as some new machines only have .net 4.7 installation by default so WinSW 2.9.0 net461 build works out-of-the-box while bin one requires installation of previous .net version.

**Comment by nikolaybespalov** [comment]
Hi

I accepted the PR.
Version 0.1.1 is coming to Maven Central soon, 
thanks a lot

**Comment by s2131** [comment]
> Version 0.1.1 is coming to Maven Central soon,

 I already see it in repository, works flawlessly.
Many thanks
