### ISSUE TITLE
rcFile is breaking winsw executable

### ISSUE THREAD

**Issue by s2131** [nikolaybespalov/winsw-maven-plugin#7]
Hi Nikolay, 
  I've tested several winsw versions and compilations and on my dev machin the rcFile configuration breaks the winsw executable that will now crash immediately in all scenarios with Exception code: 0xc0000005 (Access Violation) and Fault offset: 0x00001003. I am not an expert in ld/windres but I've tried both downgrading winsx to 2.2.0 or 1.9 and upgrading embedded ld.exe and windres.exe. Unfortunately it didn't help. I've also tried on other host but behavior is same. 

The workaround is of course to comment out <rcFile> configuration.

**Comment by nikolaybespalov** [comment]
Hmm, I'll check it out

**Comment by nikolaybespalov** [comment]
Can you provide the following information:
 - OS name
 - configuration of winsw-maven-plugin

Do you use the plugin on the same machine where you are testing it?

**Comment by s2131** [comment]
Hi the configuration is:
```xml
<plugin>
                <groupId>com.github.nikolaybespalov</groupId>
                <artifactId>winsw-maven-plugin</artifactId>
                <version>0.1.1</version>
                <executions>
                    <execution>
                        <id>process-winsw-stuff</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>winsw</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <winswVersion>2.9.0</winswVersion>
                            <winswClassifier>net461</winswClassifier>
                            <executableFileName>${project.build.finalName}.exe</executableFileName>
                            <configurationFileName>${project.build.finalName}.xml</configurationFileName>
                            <configurationFilePath>config/service/${project.artifactId}.xml</configurationFilePath>
                            <rcFile>
                                <icon>${project.basedir}/config/service/${project.artifactId}.ico</icon>
                                <fileInfo>
                                    <fileVersion>${project.version}</fileVersion>
                                    <productVersion>${project.version}</productVersion>
                                    <comments>${project.description}</comments>
                                    <companyName>${organization.name}</companyName>
                                    <copyright>${inceptionYear} ${organization.name} All Rights Reserved</copyright>
                                </fileInfo>
                            </rcFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
Tried on two systems with same results:
* Windows 10 (same machine)
* Windows Server 2019 (different machine)

As soon as I put something in rcFile section it starts to break. Tried so far following versions and classifiers and result is same regardless of which I use
* bin
* net4 
* net461
* 1.9
* 2.2.0
* 2.9.0

**Comment by s2131** [comment]
Also here is the debug log from execution of ld/windres
```
[DEBUG] Extraction /bin/win32-x86/windres.exe
[DEBUG] C:\Users\xx\AppData\Local\Temp\windres12428185918764702883.exe
[DEBUG] C:\Users\xx\AppData\Local\Temp\winsw9196377759559151988.o
[DEBUG] [C:\Users\xx\AppData\Local\Temp\windres12428185918764702883.exe, --preprocessor=type, -O, coff, -F, pe-i386, C:\Users\xx\AppData\Local\Temp\winsw1295132298016735958.rc, C:\Users\xx\AppData\Local\Temp\winsw9196377759559151988.o]
[DEBUG] Merging res and exe files
[DEBUG] Extraction /bin/win32-x86/ld.exe
[DEBUG] C:\Users\xx\AppData\Local\Temp\ld10933596685825757707.exe
[DEBUG] C:\Users\xx\AppData\Local\Temp\winsw-merged9448055315751650394.exe
[DEBUG] [C:\Users\xx\AppData\Local\Temp\ld10933596685825757707.exe, -mi386pe, --oformat, pei-i386, --dynamicbase, --nxcompat, --no-seh, -s, C:\Users\xx\AppData\Local\Temp\winsw9196377759559151988.o, C:\Users\xx\AppData\Local\Temp\winsw8099645298370047457.exe, -o, C:\Users\xx\AppData\Local\Temp\winsw-merged9448055315751650394.exe]
[INFO] The file C:\Users\xx\AppData\Local\Temp\winsw-merged9448055315751650394.exe was successfully processed.
```

**Comment by nikolaybespalov** [comment]
Hi,
I got similar results. I'm trying to figure out what's going on

**Comment by nikolaybespalov** [comment]
Hi,
I have no idea why ld.exe not working right now but I replaced it with ResourceHacker.exe. With this change, it is no longer possible to change the resources of the exe file on Linux. I'll try to think of something later.
Try to new version 0.1.5

PS: Added the install/uninstall check of the resulting exe file to the integration tests

**Comment by s2131** [comment]
Yeah, it works now. 
Still, being able to build project on Linux would be great.

**Comment by nikolaybespalov** [comment]
I'll try to find a way to workaround it on Linux. Cross-compiling is the main feature.

**Comment by nikolaybespalov** [comment]
Now the plugin can change the resources of the exe file on both Linux and macOS. Try to new version 0.1.7.

peresed is the great tool.

**Comment by nikolaybespalov** [comment]
Hi,
Windows Defender believes that the executable file created with PyInstaller/py2exe contains a virus. Executable file created with Nuitka works fine on Windows 10 but dont work on Windows 7. I had to go back to ResourceHacker for Windows. Linux/mac OS is still works on peresed because VirusTotal does not see threats in executable files.

Version 0.1.8
