### ISSUE TITLE
Request: pre-packaged winsw

### ISSUE THREAD

**Issue by leovic0101** [nikolaybespalov/winsw-maven-plugin#8]
Would it be possible to have a winsw executable embedded in the packaged jar? 
This way you also you provide an option to offline builds.

It could be an override parameter in pom file. It defaults to what it is now but give option to use the attached winsw.

Thanks.

**Comment by nikolaybespalov** [comment]
I understand your idea. But if you are working in offline mode, you first need to download the plugin, and when you first start, winsw will be downloaded.
The plugin is able to work in offline mode if winsw has already been downloaded.

Are you not satisfied with this behavior?

**Comment by leovic0101** [comment]
The problem is that the build uses an internal repository. Public respositories like https://repo.jenkins-ci.org is currently not allowed.  
We are able to import artifact from Maven repo through an onboarding process but nothing else.

**Comment by nikolaybespalov** [comment]
I'm trying to figure out how to help you. GET https://repo.jenkins-ci.org/releases/ will not return 200? I want to do without additional options. If there is no access, then you need to take the artifact from the jar

**Comment by nikolaybespalov** [comment]
Is the executableFilePath option not suitable for you? You can download what you need and store it in your repo

**Comment by leovic0101** [comment]
> I'm trying to figure out how to help you. GET https://repo.jenkins-ci.org/releases/ will not return 200? I want to do without additional options. If there is no access, then you need to take the artifact from the jar

Yes, that is a restricted URL in our network

**Comment by leovic0101** [comment]
> Is the executableFilePath option not suitable for you? You can download what you need and store it in your repo

yes, that is my other option but thought it would be cleaner so our source control does not have binaries with it.

**Comment by nikolaybespalov** [comment]
I will add the `<winswRepo>jar</winswRepo>` option. If https://repo.jenkins-ci.org/releases/ unreachable, then the artifacts will be unpacked from the jar.

**Comment by nikolaybespalov** [comment]
Try version 0.1.9

**Comment by leovic0101** [comment]
This worked! 

Thanks, @nikolaybespalov.

Appreciate your help.

**Comment by leovic0101** [comment]
By the way, I am getting a weird error on the build server. Why do we need Python? Also is 3.6 the minimum version needed?

This is the error I am getting: 

Error loading Python lib '/tmp/_MEIMNEpSA/libpython3.6m.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIMNEpSA/libpython3.6m.so.1.0) ->

**Comment by nikolaybespalov** [comment]
Python is not needed by design. I have to check on the target machine. What OS does your build server use?

**Comment by leovic0101** [comment]
I use Linux (RHEL) build server

**Comment by nikolaybespalov** [comment]
Can you show the result of the execution `ldd --version`?

**Comment by leovic0101** [comment]
ldd version is 2.17

**Comment by leovic0101** [comment]
By the way, I did bypass the rcFile generation as we don't need it. I am now able to build. 
Thanks for the great work!

**Comment by nikolaybespalov** [comment]
I found a solution anyway

**Comment by leovic0101** [comment]
> I found a solution anyway

Awesome! Appreciate your help.

**Comment by nikolaybespalov** [comment]
Try version 0.1.10

**Comment by leovic0101** [comment]
Thanks @nikolaybespalov !
It is building now.
